"use strict";

var Instance =
{
	IW_PROPERTY_ATTR_STR_FLAT : 1,       IW_PROPERTY_ATTR_END_FLAT : 2,       IW_PROPERTY_ATTR_AGI_FLAT : 3,       IW_PROPERTY_ATTR_CUN_FLAT : 4,
	IW_PROPERTY_ATTR_INT_FLAT : 5,       IW_PROPERTY_ATTR_WIS_FLAT : 6,       IW_PROPERTY_ATTR_STR_PCT : 7,        IW_PROPERTY_ATTR_END_PCT : 8,
	IW_PROPERTY_ATTR_AGI_PCT : 9,        IW_PROPERTY_ATTR_CUN_PCT : 10,       IW_PROPERTY_ATTR_INT_PCT : 11,       IW_PROPERTY_ATTR_WIS_PCT : 12,
	IW_PROPERTY_MAX_HP_PCT : 13,         IW_PROPERTY_MAX_MP_PCT : 14,         IW_PROPERTY_MAX_SP_FLAT : 15,        IW_PROPERTY_MAX_SP_PCT : 16,
	IW_PROPERTY_SP_REGEN_FLAT : 17,      IW_PROPERTY_SP_REGEN_PCT : 18,       IW_PROPERTY_MAX_SP_REGEN : 19,       IW_PROPERTY_HP_REGEN_FLAT : 20,
	IW_PROPERTY_HP_REGEN_PCT : 21,       IW_PROPERTY_MAX_HP_REGEN : 22,       IW_PROPERTY_MP_REGEN_FLAT : 23,      IW_PROPERTY_MP_REGEN_PCT : 24,
	IW_PROPERTY_MAX_MP_REGEN : 25,       IW_PROPERTY_ATTACK_RANGE : 26,       IW_PROPERTY_BASE_ATTACK_FLAT : 27,   IW_PROPERTY_BASE_ATTACK_PCT : 28,
	IW_PROPERTY_ATTACK_HP_FLAT : 29,     IW_PROPERTY_ATTACK_HP_PCT : 30,      IW_PROPERTY_ATTACK_MP_FLAT : 31,     IW_PROPERTY_ATTACK_MP_PCT : 32,
	IW_PROPERTY_ATTACK_SP_FLAT : 33,     IW_PROPERTY_ATTACK_SP_PCT : 34,      IW_PROPERTY_RUN_SP_FLAT : 35,        IW_PROPERTY_RUN_SP_PCT : 36,         
	IW_PROPERTY_MOVE_SPEED_FLAT : 37,    IW_PROPERTY_MOVE_SPEED_PCT : 38,     IW_PROPERTY_CAST_SPEED : 39,         IW_PROPERTY_SPELLPOWER : 40,
	IW_PROPERTY_CRIT_CHANCE_FLAT : 41,   IW_PROPERTY_CRIT_MULTI_FLAT : 42,    IW_PROPERTY_CRIT_CHANCE_PCT : 43,    IW_PROPERTY_CRIT_MULTI_PCT : 44,
	IW_PROPERTY_ARMOR_CRUSH_FLAT : 45,   IW_PROPERTY_ARMOR_SLASH_FLAT : 46,   IW_PROPERTY_ARMOR_PIERCE_FLAT : 47,  IW_PROPERTY_ARMOR_CRUSH_PCT : 48,
    IW_PROPERTY_ARMOR_SLASH_PCT : 49,    IW_PROPERTY_ARMOR_PIERCE_PCT : 50,   IW_PROPERTY_IGNORE_ARMOR_FLAT : 51,  IW_PROPERTY_IGNORE_ARMOR_PCT : 52,
	IW_PROPERTY_EXPERIENCE_MULTI : 53,   IW_PROPERTY_PRICE_MULTI : 54,        IW_PROPERTY_RESIST_PHYS : 55,        IW_PROPERTY_RESIST_FIRE : 56,
	IW_PROPERTY_RESIST_COLD : 57,        IW_PROPERTY_RESIST_LIGHT : 58,       IW_PROPERTY_RESIST_DEATH : 59,       IW_PROPERTY_RESMAX_PHYS : 60,
	IW_PROPERTY_RESMAX_FIRE : 61,        IW_PROPERTY_RESMAX_COLD : 62,        IW_PROPERTY_RESMAX_LIGHT : 63,       IW_PROPERTY_RESMAX_DEATH : 64,
	IW_PROPERTY_ACCURACY_FLAT : 65,      IW_PROPERTY_ACCURACY_PCT : 66,       IW_PROPERTY_DODGE_FLAT : 67,         IW_PROPERTY_DODGE_PCT : 68, 	
	IW_PROPERTY_BUFF_SELF : 69,          IW_PROPERTY_DEBUFF_SELF : 70,        IW_PROPERTY_BUFF_OTHER : 71,         IW_PROPERTY_DEBUFF_OTHER : 72,
	IW_PROPERTY_HEAL_MULTI : 73,         IW_PROPERTY_DAMAGE_MULTI : 74,       IW_PROPERTY_FATIGUE_MULTI : 75,      IW_PROPERTY_DRAIN_MULTI : 76,
	IW_PROPERTY_STATUS_STUN : 77,        IW_PROPERTY_STATUS_SLOW : 78,        IW_PROPERTY_STATUS_SILENCE : 79,     IW_PROPERTY_STATUS_ROOT : 80,
	IW_PROPERTY_STATUS_DISARM : 81,      IW_PROPERTY_STATUS_PACIFY : 82,      IW_PROPERTY_STATUS_WEAKEN : 83,      IW_PROPERTY_STATUS_SLEEP : 84,
	IW_PROPERTY_STATUS_FEAR : 85,        IW_PROPERTY_STATUS_CHARM : 86,       IW_PROPERTY_STATUS_ENRAGE : 87,      IW_PROPERTY_STATUS_EXHAUST : 88,
	IW_PROPERTY_STATUS_FREEZE : 89,      IW_PROPERTY_STATUS_CHILL : 90,       IW_PROPERTY_STATUS_WET : 91,         IW_PROPERTY_STATUS_BURNING : 92,
	IW_PROPERTY_STATUS_POISON : 93,      IW_PROPERTY_STATUS_BLEED : 94,       IW_PROPERTY_STATUS_BLIND : 95,       IW_PROPERTY_STATUS_PETRIFY : 96,
	IW_PROPERTY_DEFENSE_PHYS : 97,       IW_PROPERTY_DEFENSE_MAGIC : 98,      IW_PROPERTY_AVOID_BASH : 99,         IW_PROPERTY_AVOID_MAIM : 100,
	IW_PROPERTY_AVOID_BLEED : 101,       IW_PROPERTY_AVOID_BURN : 102,        IW_PROPERTY_AVOID_CHILL : 103,       IW_PROPERTY_AVOID_SHOCK : 104,
	IW_PROPERTY_AVOID_WEAKEN : 105,      IW_PROPERTY_AVOID_CRIT : 106,        IW_PROPERTY_CHANCE_BASH : 107,       IW_PROPERTY_CHANCE_MAIM : 108,
	IW_PROPERTY_CHANCE_BLEED : 109,      IW_PROPERTY_CHANCE_BURN : 110,       IW_PROPERTY_CHANCE_CHILL : 111,      IW_PROPERTY_CHANCE_SHOCK : 112,
	IW_PROPERTY_CHANCE_WEAKEN : 113,     IW_PROPERTY_DMG_PURE_BASE : 114,     IW_PROPERTY_DMG_CRUSH_BASE : 115,    IW_PROPERTY_DMG_SLASH_BASE : 116,
	IW_PROPERTY_DMG_PIERCE_BASE : 117,   IW_PROPERTY_DMG_FIRE_BASE : 118,     IW_PROPERTY_DMG_COLD_BASE : 119,     IW_PROPERTY_DMG_LIGHT_BASE : 120,
	IW_PROPERTY_DMG_DEATH_BASE : 121,    IW_PROPERTY_DMG_PURE_VAR : 122,      IW_PROPERTY_DMG_CRUSH_VAR : 123,     IW_PROPERTY_DMG_SLASH_VAR : 124,
	IW_PROPERTY_DMG_PIERCE_VAR : 125,    IW_PROPERTY_DMG_FIRE_VAR : 126,      IW_PROPERTY_DMG_COLD_VAR : 127,      IW_PROPERTY_DMG_LIGHT_VAR : 128,
	IW_PROPERTY_DMG_DEATH_VAR : 129,     IW_PROPERTY_DMG_PURE_PCT : 130,      IW_PROPERTY_DMG_PHYS_PCT : 131,      IW_PROPERTY_DMG_FIRE_PCT : 132,
	IW_PROPERTY_DMG_COLD_PCT : 133,      IW_PROPERTY_DMG_LIGHT_PCT : 134,     IW_PROPERTY_DMG_DEATH_PCT : 135,     IW_PROPERTY_DMG_DOT_PCT : 136,
	IW_PROPERTY_LIFESTEAL_PCT : 137,     IW_PROPERTY_LIFESTEAL_RATE : 138,    IW_PROPERTY_MANASHIELD_PCT : 139,    IW_PROPERTY_SECONDWIND_PCT : 140,
	IW_PROPERTY_SKILL_FIRE : 141,        IW_PROPERTY_SKILL_EARTH : 142,       IW_PROPERTY_SKILL_WATER : 143,       IW_PROPERTY_SKILL_AIR : 144,
	IW_PROPERTY_SKILL_LIGHT : 145,       IW_PROPERTY_SKILL_SHADOW : 146,      IW_PROPERTY_SKILL_BODY : 147,        IW_PROPERTY_SKILL_MIND : 148,      
	IW_PROPERTY_SKILL_NATURE : 149,      IW_PROPERTY_SKILL_DEATH : 150,       IW_PROPERTY_SKILL_DIVINE : 151,      IW_PROPERTY_SKILL_SHAPE : 152,
	IW_PROPERTY_SKILL_META : 153,        IW_PROPERTY_SKILL_TWOHAND : 154,     IW_PROPERTY_SKILL_ONEHAND : 155,     IW_PROPERTY_SKILL_MARKSMAN : 156,
	IW_PROPERTY_SKILL_UNARMED : 157,     IW_PROPERTY_SKILL_ARMOR : 158,       IW_PROPERTY_SKILL_COMBAT : 159,      IW_PROPERTY_SKILL_ATHLETICS : 160,
	IW_PROPERTY_SKILL_SURVIVAL : 161,    IW_PROPERTY_SKILL_PERCEPTION : 162,  IW_PROPERTY_SKILL_LORE : 163,        IW_PROPERTY_SKILL_SPEECH : 164,
	IW_PROPERTY_SKILL_STEALTH : 165,     IW_PROPERTY_SKILL_THIEVERY : 166,    IW_PROPERTY_ATTRIBUTE_POINTS : 167,  IW_PROPERTY_SKILL_POINTS : 168,
	IW_PROPERTY_MOVE_NOISE_FLAT : 169,   IW_PROPERTY_MOVE_NOISE_PCT : 170,    IW_PROPERTY_CAST_NOISE_FLAT : 171,   IW_PROPERTY_CAST_NOISE_PCT : 172,
	IW_PROPERTY_DARK_SIGHT_PCT : 173,    IW_PROPERTY_VISIBILITY_FLAT : 174,   IW_PROPERTY_VISIBILITY_PCT : 175,    IW_PROPERTY_BEHAVIOR_AGGRO : 176,
	IW_PROPERTY_BEHAVIOR_COOP : 177,     IW_PROPERTY_BEHAVIOR_SAFETY : 178,   IW_PROPERTY_CORPSE_TIME : 179,       IW_PROPERTY_ATK_SPEED_DUMMY : 180,
	IW_PROPERTY_SP_REGEN_TIME_PCT : 181, IW_PROPERTY_THREAT_MULTI : 182,      IW_PROPERTY_VISION_RANGE_FLAT : 183, IW_PROPERTY_VISION_RANGE_PCT : 184,
};

function GetBasePropertyValue(hInstance, nProperty)
{
	return hInstance.properties_base[String(nProperty)]
}

function GetBonusPropertyValue(hInstance, nProperty)
{
	return hInstance.properties_bonus[String(nProperty)]
}

function GetPropertyValue(hInstance, nProperty)
{
	return hInstance.properties_base[String(nProperty)] + hInstance.properties_bonus[String(nProperty)];
}

function GetAttributeValue(hInstance, nAttribute)
{
	return GetPropertyValue(hInstance, nAttribute) * (1.0 + GetPropertyValue(hInstance, nAttribute + 6)/100.0);
}