"use strict";

var Instance =
{
	IW_PROPERTY_ATTR_STR_FLAT : 1,       IW_PROPERTY_ATTR_CON_FLAT : 2,       IW_PROPERTY_ATTR_AGI_FLAT : 3,       IW_PROPERTY_ATTR_PER_FLAT : 4,
	IW_PROPERTY_ATTR_INT_FLAT : 5,       IW_PROPERTY_ATTR_WIS_FLAT : 6,       IW_PROPERTY_ATTR_STR_PCT : 7,        IW_PROPERTY_ATTR_CON_PCT : 8,
	IW_PROPERTY_ATTR_AGI_PCT : 9,        IW_PROPERTY_ATTR_PER_PCT : 10,       IW_PROPERTY_ATTR_INT_PCT : 11,       IW_PROPERTY_ATTR_WIS_PCT : 12,
	IW_PROPERTY_MAX_SP_FLAT : 13,        IW_PROPERTY_MAX_SP_PCT : 14,         IW_PROPERTY_SP_RECHARGE_TIME : 15,   IW_PROPERTY_SP_RECHARGE_PCT : 16,
	IW_PROPERTY_SP_REGEN_FLAT : 17,      IW_PROPERTY_SP_REGEN_PCT : 18,       IW_PROPERTY_MAX_SP_REGEN : 19,       IW_PROPERTY_HP_LIFESTEAL : 20,
	IW_PROPERTY_HP_REGEN_FLAT : 21,      IW_PROPERTY_HP_REGEN_PCT : 22,       IW_PROPERTY_MAX_HP_REGEN : 23,       IW_PROPERTY_MP_REGEN_FLAT : 24,
	IW_PROPERTY_MP_REGEN_PCT : 25,       IW_PROPERTY_MAX_MP_REGEN : 26,       IW_PROPERTY_VISION_RANGE_FLAT : 27,  IW_PROPERTY_VISION_RANGE_PCT : 28,
	IW_PROPERTY_EFFECTIVE_HP : 29,       IW_PROPERTY_ATTACK_RANGE : 30,       IW_PROPERTY_BASE_ATTACK_FLAT : 31,   IW_PROPERTY_BASE_ATTACK_PCT : 32,
	IW_PROPERTY_ATTACK_HP_FLAT : 33,     IW_PROPERTY_ATTACK_MP_FLAT : 34,     IW_PROPERTY_ATTACK_SP_FLAT : 35,     IW_PROPERTY_HP_COST_PCT : 36,
	IW_PROPERTY_MP_COST_PCT : 37,        IW_PROPERTY_SP_COST_PCT : 38,        IW_PROPERTY_RUN_SP_FLAT : 39,        IW_PROPERTY_RUN_SP_PCT : 40,         
	IW_PROPERTY_MOVE_SPEED_FLAT : 41,    IW_PROPERTY_MOVE_SPEED_PCT : 42,     IW_PROPERTY_CAST_SPEED : 43,         IW_PROPERTY_SPELLPOWER : 44,
	IW_PROPERTY_CRIT_CHANCE_FLAT : 45,   IW_PROPERTY_CRIT_MULTI_FLAT : 46,    IW_PROPERTY_CRIT_CHANCE_PCT : 47,    IW_PROPERTY_CRIT_MULTI_PCT : 48,
	IW_PROPERTY_ARMOR_CRUSH_FLAT : 49,   IW_PROPERTY_ARMOR_SLASH_FLAT : 50,   IW_PROPERTY_ARMOR_PIERCE_FLAT : 51,  IW_PROPERTY_ARMOR_CRUSH_PCT : 52,
    IW_PROPERTY_ARMOR_SLASH_PCT : 53,    IW_PROPERTY_ARMOR_PIERCE_PCT : 54,   IW_PROPERTY_IGNORE_ARMOR_FLAT : 55,  IW_PROPERTY_IGNORE_ARMOR_PCT : 56,
	IW_PROPERTY_RESIST_PHYS : 57,        IW_PROPERTY_RESIST_FIRE : 58,        IW_PROPERTY_RESIST_COLD : 59,        IW_PROPERTY_RESIST_LIGHT : 60,
	IW_PROPERTY_RESIST_DEATH : 61,       IW_PROPERTY_RESMAX_PHYS : 62,        IW_PROPERTY_RESMAX_FIRE : 63,        IW_PROPERTY_RESMAX_COLD : 64,
	IW_PROPERTY_RESMAX_LIGHT : 65,       IW_PROPERTY_RESMAX_DEATH : 66,       IW_PROPERTY_ACCURACY_FLAT : 67,      IW_PROPERTY_ACCURACY_PCT : 68,
	IW_PROPERTY_DODGE_FLAT : 69,         IW_PROPERTY_DODGE_PCT : 70, 	      IW_PROPERTY_BUFF_SELF : 71,          IW_PROPERTY_DEBUFF_SELF : 72,
	IW_PROPERTY_BUFF_OTHER : 73,         IW_PROPERTY_DEBUFF_OTHER : 74,       IW_PROPERTY_HEAL_MULTI : 75,         IW_PROPERTY_DAMAGE_MULTI : 76,
	IW_PROPERTY_THREAT_MULTI : 77,       IW_PROPERTY_FATIGUE_MULTI : 78,      IW_PROPERTY_PRICE_MULTI : 79,        IW_PROPERTY_EXP_MULTI : 80,
	IW_PROPERTY_STATUS_STUN : 81,        IW_PROPERTY_STATUS_SLOW : 82,        IW_PROPERTY_STATUS_SILENCE : 83,     IW_PROPERTY_STATUS_ROOT : 84,
	IW_PROPERTY_STATUS_DISARM : 85,      IW_PROPERTY_STATUS_MAIM : 86,        IW_PROPERTY_STATUS_PACIFY : 87,      IW_PROPERTY_STATUS_DECAY : 88,
	IW_PROPERTY_STATUS_DISEASE : 89,     IW_PROPERTY_STATUS_SLEEP : 90,       IW_PROPERTY_STATUS_FEAR : 91,        IW_PROPERTY_STATUS_CHARM : 92,
	IW_PROPERTY_STATUS_ENRAGE : 93,      IW_PROPERTY_STATUS_EXHAUST : 94,     IW_PROPERTY_STATUS_FREEZE : 95,      IW_PROPERTY_STATUS_CHILL : 96,
	IW_PROPERTY_STATUS_WET : 97,         IW_PROPERTY_STATUS_WARM : 98,        IW_PROPERTY_STATUS_BURNING : 99,     IW_PROPERTY_STATUS_POISON : 100,
	IW_PROPERTY_STATUS_BLEED : 101,      IW_PROPERTY_STATUS_BLIND : 102,      IW_PROPERTY_STATUS_DEAF : 103,       IW_PROPERTY_STATUS_PETRIFY : 104,
	IW_PROPERTY_DEFENSE_PHYS : 105,      IW_PROPERTY_DEFENSE_MAGIC : 106,     IW_PROPERTY_AVOID_BASH : 107,        IW_PROPERTY_AVOID_MAIM : 108,
	IW_PROPERTY_AVOID_BLEED : 109,       IW_PROPERTY_AVOID_BURN : 110,        IW_PROPERTY_AVOID_CHILL : 111,       IW_PROPERTY_AVOID_SHOCK : 112,
	IW_PROPERTY_AVOID_DECAY : 113,       IW_PROPERTY_AVOID_CRIT : 114,        IW_PROPERTY_CHANCE_BASH : 115,       IW_PROPERTY_CHANCE_MAIM : 116,
	IW_PROPERTY_CHANCE_BLEED : 117,      IW_PROPERTY_CHANCE_BURN : 118,       IW_PROPERTY_CHANCE_CHILL : 119,      IW_PROPERTY_CHANCE_SHOCK : 120,
	IW_PROPERTY_CHANCE_DECAY : 121,      IW_PROPERTY_DMG_PURE_BASE : 122,     IW_PROPERTY_DMG_CRUSH_BASE : 123,    IW_PROPERTY_DMG_SLASH_BASE : 124,
	IW_PROPERTY_DMG_PIERCE_BASE : 125,   IW_PROPERTY_DMG_FIRE_BASE : 126,     IW_PROPERTY_DMG_COLD_BASE : 127,     IW_PROPERTY_DMG_LIGHT_BASE : 128,
	IW_PROPERTY_DMG_DEATH_BASE : 129,    IW_PROPERTY_DMG_PURE_VAR : 130,      IW_PROPERTY_DMG_CRUSH_VAR : 131,     IW_PROPERTY_DMG_SLASH_VAR : 132,
	IW_PROPERTY_DMG_PIERCE_VAR : 133,    IW_PROPERTY_DMG_FIRE_VAR : 134,      IW_PROPERTY_DMG_COLD_VAR : 135,      IW_PROPERTY_DMG_LIGHT_VAR : 136,
	IW_PROPERTY_DMG_DEATH_VAR : 137,     IW_PROPERTY_DMG_PURE_PCT : 138,      IW_PROPERTY_DMG_PHYS_PCT : 139,      IW_PROPERTY_DMG_FIRE_PCT : 140,
	IW_PROPERTY_DMG_COLD_PCT : 141,      IW_PROPERTY_DMG_LIGHT_PCT : 142,     IW_PROPERTY_DMG_DEATH_PCT : 143,     IW_PROPERTY_DMG_DOT_PCT : 144,
	IW_PROPERTY_LIFESTEAL_PCT : 145,     IW_PROPERTY_LIFESTEAL_RATE : 146,    IW_PROPERTY_MANASHIELD_PCT : 147,    IW_PROPERTY_SECONDWIND_PCT : 148,
	IW_PROPERTY_SKILL_FIRE : 149,        IW_PROPERTY_SKILL_EARTH : 150,       IW_PROPERTY_SKILL_WATER : 151,       IW_PROPERTY_SKILL_AIR : 152,
	IW_PROPERTY_SKILL_LIGHT : 153,       IW_PROPERTY_SKILL_SHADOW : 154,      IW_PROPERTY_SKILL_BODY : 155,        IW_PROPERTY_SKILL_MIND : 156,      
	IW_PROPERTY_SKILL_LIFE : 157,        IW_PROPERTY_SKILL_DEATH : 158,       IW_PROPERTY_SKILL_SHAPE : 159,       IW_PROPERTY_SKILL_METAMAGIC : 160,
	IW_PROPERTY_SKILL_TWOHAND : 161,     IW_PROPERTY_SKILL_ONEHAND : 162,     IW_PROPERTY_SKILL_MARKSMAN : 163,    IW_PROPERTY_SKILL_DUALWIELD : 164,
	IW_PROPERTY_SKILL_ARMOR : 165,       IW_PROPERTY_SKILL_COMBAT : 166,      IW_PROPERTY_SKILL_LEADERSHIP : 167,  IW_PROPERTY_SKILL_SURVIVAL : 168,
	IW_PROPERTY_SKILL_LORE : 169,        IW_PROPERTY_SKILL_SPEECH : 170,      IW_PROPERTY_SKILL_STEALTH : 171,     IW_PROPERTY_SKILL_THIEVERY : 172,
	IW_PROPERTY_ATTRIBUTE_POINTS : 173,  IW_PROPERTY_SKILL_POINTS : 174,      IW_PROPERTY_CARRY_CAPACITY : 175,    IW_PROPERTY_EQUIP_WEIGHT_PCT : 176,
	IW_PROPERTY_MOVE_NOISE_FLAT : 177,   IW_PROPERTY_MOVE_NOISE_PCT : 178,    IW_PROPERTY_CAST_NOISE_FLAT : 179,   IW_PROPERTY_CAST_NOISE_PCT : 180,
	IW_PROPERTY_DARK_SIGHT_PCT : 181,    IW_PROPERTY_VISIBILITY_FLAT : 182,   IW_PROPERTY_VISIBILITY_PCT : 183,    IW_PROPERTY_NOISE_THRESHOLD : 184,
	IW_PROPERTY_VISION_THRESHOLD : 185,  IW_PROPERTY_VISION_MASK : 186,       IW_PROPERTY_THREAT_RADIUS : 187,     IW_PROPERTY_SHARE_RADIUS : 188,
	IW_PROPERTY_THREAT_SHARE_PCT : 189,  IW_PROPERTY_CORPSE_TIME : 190,       IW_PROPERTY_ATK_SPEED_DUMMY : 191,
};

function GetBasePropertyValue(hInstance, nProperty)
{
	return hInstance.properties_base[String(nProperty)]
}

function GetBonusPropertyValue(hInstance, nProperty)
{
	return hInstance.properties_bonus[String(nProperty)]
}

function GetPropertyValue(hInstance, nProperty)
{
	return hInstance.properties_base[String(nProperty)] + hInstance.properties_bonus[String(nProperty)];
}

function GetAttributeValue(hInstance, nAttribute)
{
	return GetPropertyValue(hInstance, nAttribute) * (1.0 + GetPropertyValue(hInstance, nAttribute + 6)/100.0);
}